require 'base'
require 'donald_trump'
require 'barack_obama'
require 'hillary_clinton'
require 'speeches/donald_trump_speech'
require 'speeches/barack_obama_speech'
require 'speeches/hillary_clinton_speech'